### ISSUE TITLE
Is this compatible with angular 5.0 and above

### ISSUE THREAD

**Issue by Kailash0593** [vinaygopinath/ng2-meta#44]
I followed the documentation but getting below error:
**Uncaught Error: Can't resolve all parameters for MetaService**

As i did some research on meta, is it already present in angular 5.0 ?
**https://angular.io/api/platform-browser/Meta**

**Comment by AzizjonRashidov** [comment]
I have the same problem with angular 5.2, any help would be great!

**Comment by mcblum** [comment]
As do I. If anyone figures this out, post here!

**Comment by mcblum** [comment]
Ok actually I figured it out :) I'll make a PR shortly but basically the issue is that `META_CONFIG` is using something called `OpaqueToken` which I've never seen before. I changed the line in the core module to `export const META_CONFIG = new InjectionToken<MetaConfig>('META_CONFIG');`

In addition, you have to move `META_CONFIG` to a new file because otherwise it's defined in the module which requires the service and used in the service which then requires the module file. Simply moving that definition to its own `config.ts` file solved that problem and the lib now works.

**Comment by vinaygopinath** [comment]
Hi, please use the just-released [v3.0.0](https://github.com/vinaygopinath/ng2-meta/releases/tag/v3.0.0) that is compatible with Angular 5.x.

@mcblum Good catch, thanks :) I've replaced `OpaqueToken` (which was deprecated in Angular v4 and removed in v5) with `InjectionToken`.
