### ISSUE TITLE
Upgrading to Angular 6 gives error this.router.events.filter is not a function

### ISSUE THREAD

**Issue by bh-rat** [vinaygopinath/ng2-meta#45]
Hi,

Upgrading to Angular 6 gives the following error :
ERROR Error: Uncaught (in promise): TypeError: this.router.events.filter is not a function
TypeError: this.router.events.filter is not a function

I am using rxjs 6 and most probably, the change needed is that map and filter needs to be called using pipe function. Maybe the guide here : https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md might help.

**Comment by vinaygopinath** [comment]
Hey @bh-rat,

Thanks for reporting this. I haven't had a chance to test for compatibility with angular 6/rxjs 6 yet.

If anyone's interested in making a PR for it (bump dependencies, migrate to rxjs 6, fix other breaking changes due to migration to angular 6), please let me know below - I'd be happy to accept it. If not, I should be able to work on it next week.

**Comment by vinaygopinath** [comment]
Fixed - ng2-meta now supports Angular 6/rxjs 6+ in v5.0.0

Side note - I should've spotted it sooner, but the error you mention (`this.router.events.filter is not a function`) is related to code that is no longer in use (v2.0.3 or lower). Please upgrade to a newer version.
